In [1]:
import numpy as np

Напишите код, моделирующий выпадение поля в рулетке (с учетом поля зеро).

In [4]:
np.random.randint(0, 36)

13

Напишите код, проверяющий любую из теорем сложения или умножения вероятности на примере рулетки или подбрасывания монетки.

In [19]:
k = 0
m = 0
pk = 0.5
pm = 0.5
for i in range(1):
    np.random.uniform(0, 10)
    if i > 5:
        k += 1
    else:
        m += 1
if (pk + pm) == k or (pk + pm) == m:
    print('выпал или oрел или решка')

выпал или oрел или решка


Сгенерируйте десять выборок случайных чисел х0, …, х9. и постройте гистограмму распределения случайной суммы х0+х1+ …+ х9.

In [10]:
x0 = np.random.randn(10)
x1 = np.random.randn(10)
x2 = np.random.randn(10)
x3 = np.random.randn(10)
x4 = np.random.randn(10)
x5 = np.random.randn(10)
x6 = np.random.randn(10)
x7 = np.random.randn(10)
x8 = np.random.randn(10)
x9 = np.random.randn(10)
x_sum = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9
x_sum

array([ 2.52489701, -0.60433217,  2.90869467, -3.03551737,  0.64515126,
        3.30676053, -4.44814459, -1.39174333,  2.96173445,  3.0752134 ])

In [11]:
import matplotlib.pyplot as plt

In [13]:
plt.hist(x_sum)

(array([1., 1., 0., 1., 1., 0., 1., 0., 1., 4.]),
 array([-4.44814459, -3.67265408, -2.89716357, -2.12167305, -1.34618254,
        -0.57069203,  0.20479848,  0.98028899,  1.7557795 ,  2.53127002,
         3.30676053]),
 <a list of 10 Patch objects>)

Дополните код Монте-Карло последовательности независимых испытаний расчетом соответствующих вероятностей (через биномиальное распределение) 
и сравните результаты.

In [ ]:
k = 0
m = 0
pk = 0.5
pm = 0.5
for i in range(1):
    np.random.uniform(0, 10)
    if i > 5:
        k += 1
    else:
        m += 1